### ISSUE TITLE
Version 0.2.1 fails to apply to existing service with Terraform Cloud

### ISSUE THREAD

**Issue by clawrence121** [ClickHouse/terraform-provider-clickhouse#115]
I have updated the provider from `0.2.0` to `0.2.1` and am failing to apply changes when running on Terraform Cloud:
![CleanShot 2024-08-06 at 18 04 21@2x](https://github.com/user-attachments/assets/27b0f361-90ef-4d59-9541-56afea34d56f)
`0.2.0` deploys successfully on revert.
Unsure if this will work in Terraform CLI, unable to test with our current TF configuration.

Possibly as a result of: https://github.com/ClickHouse/terraform-provider-clickhouse/pull/105

Here is the full log:
```
Terraform v1.8.5
on linux_amd64
Initializing plugins and modules...
{"@level":"info","@message":"Terraform 1.8.5","@module":"terraform.ui","@timestamp":"2024-08-06T16:29:44.044839Z","terraform":"1.8.5","type":"version","ui":"1.2"}
{"@level":"info","@message":"module.clickhouse.clickhouse_service.insights_service: Plan to update","@module":"terraform.ui","@timestamp":"2024-08-06T16:29:47.102644Z","change":{"resource":{"addr":"module.clickhouse.clickhouse_service.insights_service","module":"module.clickhouse","resource":"clickhouse_service.insights_service","implied_provider":"clickhouse","resource_type":"clickhouse_service","resource_name":"insights_service","resource_key":null},"action":"update"},"type":"planned_change"}
{"@level":"info","@message":"module.clickhouse.clickhouse_service.insights_service: Modifying... [id=3b3784fc-c65d-431f-a0bf-86117b024cc5]","@module":"terraform.ui","@timestamp":"2024-08-06T16:29:47.566754Z","hook":{"resource":{"addr":"module.clickhouse.clickhouse_service.insights_service","module":"module.clickhouse","resource":"clickhouse_service.insights_service","implied_provider":"clickhouse","resource_type":"clickhouse_service","resource_name":"insights_service","resource_key":null},"action":"update","id_key":"id","id_value":"3b3784fc-c65d-431f-a0bf-86117b024cc5"},"type":"apply_start"}
{"@level":"info","@message":"module.clickhouse.clickhouse_service.insights_service: Modifications errored after 3s","@module":"terraform.ui","@timestamp":"2024-08-06T16:29:51.351765Z","hook":{"resource":{"addr":"module.clickhouse.clickhouse_service.insights_service","module":"module.clickhouse","resource":"clickhouse_service.insights_service","implied_provider":"clickhouse","resource_type":"clickhouse_service","resource_name":"insights_service","resource_key":null},"action":"update","elapsed_seconds":3},"type":"apply_errored"}
{"@level":"error","@message":"Error: Provider produced inconsistent result after apply","@module":"terraform.ui","@timestamp":"2024-08-06T16:29:59.302003Z","diagnostic":{"severity":"error","summary":"Provider produced inconsistent result after apply","detail":"When applying changes to module.clickhouse.clickhouse_service.insights_service, provider \"provider[\\\"registry.terraform.io/clickhouse/clickhouse\\\"]\" produced an unexpected new value: .encryption_assumed_role_identifier: was null, but now cty.StringVal(\"\").\n\nThis is a bug in the provider, which should be reported in the provider's own issue tracker."},"type":"diagnostic"}
{"@level":"error","@message":"Error: Provider produced inconsistent result after apply","@module":"terraform.ui","@timestamp":"2024-08-06T16:29:59.302225Z","diagnostic":{"severity":"error","summary":"Provider produced inconsistent result after apply","detail":"When applying changes to module.clickhouse.clickhouse_service.insights_service, provider \"provider[\\\"registry.terraform.io/clickhouse/clickhouse\\\"]\" produced an unexpected new value: .encryption_key: was null, but now cty.StringVal(\"\").\n\nThis is a bug in the provider, which should be reported in the provider's own issue tracker."},"type":"diagnostic"}
Operation failed: failed running terraform apply (exit 1)
```

**Comment by clawrence121** [comment]
Looks like probably resolved in #110 ?

**Comment by whites11** [comment]
Hello @clawrence121 
thanks a lot for your bug report.

We indeed noticed this problem as well and it should be solved in the main branch already.
I will run one more test to be sure and craft a release in the next few hours.

Sorry for the inconvenience

**Comment by whites11** [comment]
Actually I'm unable to replicate this issue with 0.2.1.

Anyway I release 0.2.2, could you please test if you still have this issue?

Thanks

**Comment by clawrence121** [comment]
Hey @whites11 , thanks for the quick follow up.

Deploy for 0.2.2 is failing for a new reason:
```
Stack trace from the terraform-provider-clickhouse_v0.2.2 plugin:

panic: runtime error: comparing uncomparable type basetypes.ObjectValue

goroutine 23 [running]:
github.com/ClickHouse/terraform-provider-clickhouse/pkg/internal/tfutils.Equal[...](...)
github.com/ClickHouse/terraform-provider-clickhouse/pkg/internal/tfutils/utils.go:18
github.com/ClickHouse/terraform-provider-clickhouse/pkg/resource.(*ServiceResource).Update(0xc00063e450, {0xd4b008, 0xc00066ee40}, {{{{0xd4f950, 0xc00067de30}, {0xb314a0, 0xc00067cd50}}, {0xd51738, 0xc0004a0500}}, {{{0xd4f950, ...}, ...}, ...}, ...}, ...)
github.com/ClickHouse/terraform-provider-clickhouse/pkg/resource/service.go:555 +0x372
github.com/hashicorp/terraform-plugin-framework/internal/fwserver.(*Server).UpdateResource(0xc0002201e0, {0xd4b008, 0xc00066ee40}, 0xc000533510, 0xc0005334e8)
github.com/hashicorp/terraform-plugin-framework@v1.11.0/internal/fwserver/server_updateresource.go:122 +0x6ee
github.com/hashicorp/terraform-plugin-framework/internal/fwserver.(*Server).ApplyResourceChange(0xc0002201e0, {0xd4b008, 0xc00066ee40}, 0xc0003da280, 0xc0005336d0)
github.com/hashicorp/terraform-plugin-framework@v1.11.0/internal/fwserver/server_applyresourcechange.go:102 +0x192
github.com/hashicorp/terraform-plugin-framework/internal/proto6server.(*Server).ApplyResourceChange(0xc0002201e0, {0xd4b008?, 0xc00066ed20?}, 0xc0003da1e0)
github.com/hashicorp/terraform-plugin-framework@v1.11.0/internal/proto6server/server_applyresourcechange.go:55 +0x38e
github.com/hashicorp/terraform-plugin-go/tfprotov6/tf6server.(*server).ApplyResourceChange(0xc000230b40, {0xd4b008?, 0xc00066e180?}, 0xc000158a80)
github.com/hashicorp/terraform-plugin-go@v0.23.0/tfprotov6/tf6server/server.go:865 +0x3d0
github.com/hashicorp/terraform-plugin-go/tfprotov6/internal/tfplugin6._Provider_ApplyResourceChange_Handler({0xc00f40, 0xc000230b40}, {0xd4b008, 0xc00066e180}, 0xc0004bf680, 0x0)
github.com/hashicorp/terraform-plugin-go@v0.23.0/tfprotov6/internal/tfplugin6/tfplugin6_grpc.pb.go:518 +0x1a6
google.golang.org/grpc.(*Server).processUnaryRPC(0xc00019b200, {0xd4b008, 0xc00066e0f0}, {0xd507a0, 0xc000002180}, 0xc000668d80, 0xc00027fc20, 0x12386f8, 0x0)
google.golang.org/grpc@v1.63.2/server.go:1369 +0xdf8
google.golang.org/grpc.(*Server).handleStream(0xc00019b200, {0xd507a0, 0xc000002180}, 0xc000668d80)
google.golang.org/grpc@v1.63.2/server.go:1780 +0xe8b
google.golang.org/grpc.(*Server).serveStreams.func2.1()
google.golang.org/grpc@v1.63.2/server.go:1019 +0x8b
created by google.golang.org/grpc.(*Server).serveStreams.func2 in goroutine 11
google.golang.org/grpc@v1.63.2/server.go:1030 +0x125

Error: The terraform-provider-clickhouse_v0.2.2 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

![CleanShot 2024-08-07 at 11 05 42@2x](https://github.com/user-attachments/assets/afb64e9b-3f34-464f-9e1c-fcced660e1d9)

**Comment by clawrence121** [comment]
From looking at `service.go` it looks like this check is failing:
```
if !tfutils.Equal(plan.IpAccessList.Elements(), state.IpAccessList.Elements()) {
```

Here is my provider definition for reference, no changes have been made to the ip list:
```
resource "clickhouse_service" "insights_service" {
  name                 = "insights-${var.environment}"
  cloud_provider       = "aws"
  region               = "us-east-1"
  tier                 = "production"
  idle_scaling         = false
  idle_timeout_minutes = 15

  # memory must be a multiple of 12
  max_total_memory_gb = var.environment == "prod" ? 360 : 72
  min_total_memory_gb = var.environment == "prod" ? 72 : 24

  password = var.service_password
  ip_access = [
    {
      source      = "0.0.0.0/0"
      description = "Anywhere"
    }
  ]
}

**Comment by whites11** [comment]
uhm I can't seem to replicate this one, either.
I wonder if this is related to the terraform client version somehow.

**Comment by whites11** [comment]
would you be able to share your state file? Maybe there is a hint there.
please redact any sensible information in there!

**Comment by clawrence121** [comment]
@whites11 here you go:
```
{
  "version": 4,
  "terraform_version": "1.8.5",
  "serial": 1009,
  "lineage": "redacted",
  "outputs": {
    "clickhouse_service_host": {
      "value": "redacted",
      "type": "string"
    },
    "clickhouse_service_port": {
      "value": 8443,
      "type": "number"
    }
  },
  "resources": [
    {
      "module": "module.clickhouse",
      "mode": "managed",
      "type": "clickhouse_service",
      "name": "insights_service",
      "provider": "provider[\"registry.terraform.io/clickhouse/clickhouse\"]",
      "instances": [
        {
          "schema_version": 0,
          "attributes": {
            "cloud_provider": "aws",
            "double_sha1_password_hash": null,
            "encryption_assumed_role_identifier": null,
            "encryption_key": null,
            "endpoints": [
              {
                "host": "redacted",
                "port": 9440,
                "protocol": "nativesecure"
              },
              {
                "host": "redacted",
                "port": 8443,
                "protocol": "https"
              }
            ],
            "iam_role": "redacted",
            "id": "redacted",
            "idle_scaling": false,
            "idle_timeout_minutes": null,
            "ip_access": [
              {
                "description": "Anywhere",
                "source": "0.0.0.0/0"
              }
            ],
            "last_updated": "Tuesday, 06-Aug-24 17:11:33 UTC",
            "max_total_memory_gb": 72,
            "min_total_memory_gb": 24,
            "name": "insights-dev",
            "num_replicas": null,
            "password": "redacted",
            "password_hash": null,
            "private_endpoint_config": {
              "endpoint_service_id": "redacted",
              "private_dns_hostname": "redacted"
            },
            "private_endpoint_ids": [],
            "region": "us-east-1",
            "tier": "production"
          },
          "sensitive_attributes": [
            [
              {
                "type": "get_attr",
                "value": "double_sha1_password_hash"
              }
            ],
            [
              {
                "type": "get_attr",
                "value": "password"
              }
            ],
            [
              {
                "type": "get_attr",
                "value": "password_hash"
              }
            ]
          ]
        }
      ]
    }
  ],
  "check_results": []
}

**Comment by whites11** [comment]
Yeah they seem identical and they are pretty much identical to the one I have generated in my latest test run.
I tried upgrading to latest terraform cli, no luck.

I blindly tried to replace the comparison function with a terraform provided one, hopefully that'll help but unfortunately I have no way to test this but asking you to do it.
Thanks a lot for the cooperation @clawrence121 

version 0.2.3 is out.

**Comment by clawrence121** [comment]
@whites11 that worked!

I have tested:
- Plan (and no apply) with no changes ✅
- Apply with changes ✅

![CleanShot 2024-08-07 at 14 23 33@2x](https://github.com/user-attachments/assets/7fd1d196-3b26-4e95-ab9f-0ef573c65a32)
![CleanShot 2024-08-07 at 14 23 40@2x](https://github.com/user-attachments/assets/caa2c302-d6c6-427b-a799-e42f8c9a0478)

Thank you for the quick turn around!

**Comment by whites11** [comment]
@clawrence121 I appreciate a lot your help, thank you very much
