### ISSUE TITLE
Terraform plugin crashed

### ISSUE THREAD

**Issue by paxw-panevo** [ClickHouse/terraform-provider-clickhouse#146]
Given the plan,

```terraform
Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # module.clickhouse_service.clickhouse_private_endpoint_registration.azure_private_endpoint will be created
  + resource "clickhouse_private_endpoint_registration" "azure_private_endpoint" {
      + cloud_provider = "azure"
      + description    = "xxx-prod-vnet-yyyy"
      + id             = "xxxx"
      + region         = "eastus2"
    }

  # module.clickhouse_service.clickhouse_service.azure will be created
  + resource "clickhouse_service" "azure" {
      + cloud_provider          = "azure"
      + endpoints               = (known after apply)
      + iam_role                = (known after apply)
      + id                      = (known after apply)
      + ip_access               = []
      + last_updated            = (known after apply)
      + max_total_memory_gb     = 36
      + min_total_memory_gb     = 24
      + name                    = "xxxxx-prod-clickhouse-eaus2"
      + password                = (sensitive value)
      + private_endpoint_config = (known after apply)
      + private_endpoint_ids    = [
          + "xxxxxxxx",
        ]
      + region                  = "eastus2"
      + tier                    = "production"
    }

Plan: 2 to add, 0 to change, 0 to destroy.

Changes to Outputs:
  + clickhouse_hostname = (known after apply)
```

Applying the plan causes terraform's clickhouse plugin to crash,

```sh
module.clickhouse_service.clickhouse_service.azure: Still creating... [1m50s elapsed]
╷
│ Error: Request cancelled
│ 
│ The plugin6.(*GRPCProvider).ApplyResourceChange request was cancelled.
╵

Stack trace from the terraform-provider-clickhouse_v0.0.9 plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x8bfbab]

goroutine 99 [running]:
terraform-provider-clickhouse/clickhouse.(*ServiceResource).Create(0xc000012078, {0xdb8ba0, 0xc000566cc0}, {{{{0xdbd110, 0xc00032cf00}, {0xbac5a0, 0xc00032c5d0}}, {0xdbe6c0, 0xc0003af450}}, {{{0xdbd110, ...}, ...}, ...}, ...}, ...)
        terraform-provider-clickhouse/clickhouse/service.go:372 +0x13eb
github.com/hashicorp/terraform-plugin-framework/internal/fwserver.(*Server).CreateResource(0xc0000f9760, {0xdb8ba0, 0xc000566cc0}, 0xc0005973b0, 0xc000597350)
        github.com/hashicorp/terraform-plugin-framework@v1.3.5/internal/fwserver/server_createresource.go:101 +0x598
github.com/hashicorp/terraform-plugin-framework/internal/fwserver.(*Server).ApplyResourceChange(0xc000597508?, {0xdb8ba0, 0xc000566cc0}, 0xc0001b24b0, 0xc000597508)
        github.com/hashicorp/terraform-plugin-framework@v1.3.5/internal/fwserver/server_applyresourcechange.go:57 +0x4a8
github.com/hashicorp/terraform-plugin-framework/internal/proto6server.(*Server).ApplyResourceChange(0xc0000f9760, {0xdb8ba0?, 0xc000566b70?}, 0xc0001b23c0)
        github.com/hashicorp/terraform-plugin-framework@v1.3.5/internal/proto6server/server_applyresourcechange.go:55 +0x41a
github.com/hashicorp/terraform-plugin-go/tfprotov6/tf6server.(*server).ApplyResourceChange(0xc00017afa0, {0xdb8ba0?, 0xc000566300?}, 0xc000128070)
        github.com/hashicorp/terraform-plugin-go@v0.18.0/tfprotov6/tf6server/server.go:819 +0x574
github.com/hashicorp/terraform-plugin-go/tfprotov6/internal/tfplugin6._Provider_ApplyResourceChange_Handler({0xc62580?, 0xc00017afa0}, {0xdb8ba0, 0xc000566300}, 0xc000128000, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.18.0/tfprotov6/internal/tfplugin6/tfplugin6_grpc.pb.go:422 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0001b41e0, {0xdbd3f8, 0xc000388820}, 0xc0004e2000, 0xc000302de0, 0x128e580, 0x0)
        google.golang.org/grpc@v1.56.1/server.go:1337 +0xdf3
google.golang.org/grpc.(*Server).handleStream(0xc0001b41e0, {0xdbd3f8, 0xc000388820}, 0xc0004e2000, 0x0)
        google.golang.org/grpc@v1.56.1/server.go:1714 +0xa36
google.golang.org/grpc.(*Server).serveStreams.func1.1()
        google.golang.org/grpc@v1.56.1/server.go:959 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.56.1/server.go:957 +0x18c

Error: The terraform-provider-clickhouse_v0.0.9 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

**Comment by whites11** [comment]
> no available releases match the given constraints 0.0.9, 1.0.0

according to this error, it seems like you are requesting 2 versions of the provider for some reason. Ensure you're not requesting 0.0.9 anywhere else
